url: https://team-bi0s.github.io
baseurl: ""

# Site settings
title: Init-Labs
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Anirudh Anand
  pic: 1
  position: Web Application Security
  social:
    - title: twitter
      url: https://twitter.com/a0xnirudh
    - title: facebook
      url: https://facebook.com/a0xnirudh
    - title: linkedin
      url: https://www.linkedin.com/in/anirudhanand

- name: Seshagiri Prabhu
  pic: 2
  position: CEO
  social:
    - title: twitter
      url: #
    - title: facebook
      url: https://www.facebook.com/seshagiri.prabhu
    - title: linkedin
      url: https://in.linkedin.com/pub/seshagiri-prabhu/1b/172/8ab

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: #
  - title: facebook
    url:
  - title: stack-overflow
    url: #
  - title: bitbucket 
    url: #
  - title: github
    url: https://github.com/team-bi0s/team-bi0s.github.io

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
