url: https://team-bi0s.github.io
baseurl: ""

# Site settings
title: Init-Labs
email: your-anirudhanand722@gmail.com
description: "Security | Testing | Training"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Anirudh Anand
  pic: 1
  position: Web Application Security
  social:
    - title: twitter
      url: https://twitter.com/a0xnirudh
    - title: facebook
      url: https://facebook.com/a0xnirudh
    - title: linkedin
      url: https://www.linkedin.com/in/anirudhanand

- name: Seshagiri Prabhu
  pic: 2
  position: Android Security
  social:
    - title: twitter
      url: #
    - title: facebook
      url: https://www.facebook.com/seshagiri.prabhu
    - title: linkedin
      url: https://in.linkedin.com/pub/seshagiri-prabhu/1b/172/8ab

- name: Sreepriya Chalakkal
  pic: 3
  position: Malware Analysis
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: #
  - title: facebook
    url:
  - title: stack-overflow
    url: #
  - title: bitbucket 
    url: #
  - title: github
    url: https://github.com/team-bi0s/

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
